version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: 
          command: ./build.sh
          name: Build
          
workflows:
  main:
    jobs:
      - build-and-test
