version: 2.1

jobs:
  build-and-test:
    docker:
      - image: cimg/python:3.9.1
    steps:
      - checkout
      - run: 
          command: python -m unittest day-1/*_test.py
          name: Day 1

workflows:
  main:
    jobs:
      - build-and-test